@startuml
actor User
boundary Jenkins
control Maven
database GitHub
database "Sonatype Nexus" as Nexus
entity SonarQube as Sonar

User -> Jenkins: Runs job
Jenkins -> GitHub: Retrieve branch
Jenkins <- GitHub: Source code
Jenkins -> Maven: clean install
...
Jenkins <-- Maven: Build results
Jenkins -> Maven: sonar:sonar
Maven -> Sonar: Code check
...
Maven <-- Sonar: Job complete
Jenkins <-- Maven: Job complete
Jenkins -> Maven: deploy
Maven -> Nexus: Deploy artifacts
...
Maven <-- Nexus: Job complete
Jenkins <-- Maven: Job complete
User <-- Jenkins: Job complete

@enduml
